trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      version="0.0.3-dev"
      curl -L -o tfx "https://github.com/straubt1/tfx/releases/download/${version}/tfx_linux_amd64"
      chmod +x tfx
      ./tfx plan --tfeOrganization pcarey-demo --tfeToken $(tfx_token) -w azure-devops
